FE_PATH=$PWD/clipclutch-fe/
BE_PATH=$PWD/clipclutch-be/

CLIPCLUTCH_PATH=""
CLIPCLUTCH_SERV_PATH=""
CLIPCLUTCH_SERV_CONF_PATH=""
CLIPCLUTCH_SERV_LIB_PATH=""

CLIPCLUTCH_SERV_CONTAINER_NAME=""
CLIPCLUTCH_SERV_DOCKERFILE_NAME=""