version: '2'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ${NGINX_VOLUME_PATH}:/srv/cc/
    ports:
      - '443:443'

  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ${API_DOCKERFILE_NAME}
    volumes:
      - ${API_VOLUME_PATH}:/srv/api/
    ports:
      - "8081:8081"