version: '2'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ${NGINX_VOLUME_PATH}:/srv/cc/
    ports:
      - '443:443'

  # api:
  #   container_name:
  #   build:
  #     context: .
  #     dockerfile: dockerfile-
  #   volumes:
  #     - ''
  #   ports:
  #     - "9000:9000"